const form = document.getElementById('form')
const username = document.getElementById('form')
const email = document.getElementById('form')
const password = document.getElementById('form')
const password2 = document.getElementById('form')